### ISSUE TITLE
fluid~  in an existing .pd file 

### ISSUE THREAD

**Issue by Paavo-UEF** [porres/pd-sfont#29]
Dear gurus,
I am beginner with pd and fluidsynth.
I am using Win10 64-bit
I'd need to run set of .pd files which have fluid~  instances in them.
I received files from my collaborator who uses mac, he gave hint to use porres/pd-fluid package.
I have not succeeded to "make" nor install the pd-fluid into my win desktop:
I am using MSY2, following instructions in read me of pd-fluid. The error at the moment is:
![image](https://user-images.githubusercontent.com/67626606/173191991-c64adda6-bac8-41de-b4ba-b4e6ed53563f.png)

I've understood that the linker doenot find fluidsynth library....

I noticed that there is ceammc/fluid~... pd-files available via Pd Fined externals, but most probably they are not compatible to this fluid~ which has been used on mac to create the .pd files i am trying to run. the pd-code looks like this

![image](https://user-images.githubusercontent.com/67626606/173191873-2b61a17c-2fb6-45f7-a619-95d426a0a448.png)
(i know, dashed lines for fluid~ : not found)

The pd-fluid has been arhieved, i noticed. I have installed pd-else, but it seems not to have fluid~, rather sfont~
not sure if this is easily compatibel with fluid~

Any tips are highly appriciated and i am happy to tell about my project more to interested ones.

BR,, Paavo from Finland

**Comment by Paavo-UEF** [comment]
In short, is it possible to get pd-fluid working in win10 or should we rely on pd-else etc.

**Comment by porres** [comment]
> I've understood that the linker doenot find fluidsynth library....

yeah, you need to install it first, as explained in the readme.

> The pd-fluid has been archived, i noticed. 

yup, and it's never been properly released. It's supposed to be compatible to an old 'fluid~' object for Pd, also present in Purr Data.

> I have installed pd-else, but it seems not to have fluid~, rather sfont~
> not sure if this is easily compatible with fluid~

not really compatible, but surely an alternative where you can adapt your patch.

I am closing this issue as it is not related to 'sfont~'

**Comment by porres** [comment]
> I noticed that there is ceammc/fluid~... pd-files available via Pd Fined externals, but most probably they are not compatible to this fluid~ 

no, they're not compatible... ceammc's fluid~ has nothing to do with this older Pd object

**Comment by porres** [comment]
> In short, is it possible to get pd-fluid working in win10 or should we rely on pd-else etc.

should be possible if you know how to build it, but I don't see the point in using an object that is not being supported. I just suggest you use sfont~, once you already have else installed. The sfont~ object has more functionalities and what I consider a better design...

**Comment by Paavo-UEF** [comment]
Thanks, well, how straightforward it is to modify a pd code so that sfont~ is used instead of fluid~ ? aim to  produce similar sounds.
This is a human movement sonification pilot project :-)

**Comment by porres** [comment]
just read the help file
